services:
  - type: web
    name: mp4-webm-bot
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATABASE_PATH
        value: bot.db
